[package]
name = "two-kinect"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.9"

nusb = "=0.1.12"

zune-jpeg = "0.4.14"

tokio = { version = "*", features = ["rt-multi-thread", "macros", "time"] }
env_logger = "0.11.6"
