[package]
name = "two-kinect"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.9"

nusb = "=0.1.12"

zune-jpeg = { version = "0.4.14", optional = true }
mozjpeg = { version = "0.10.12", optional = true }
turbojpeg = { version = "1.1.1", optional = true }

tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros", "time"] }
env_logger = "0.11.6"

[features]
default = ["moz_jpeg"]
zune_jpeg = ["dep:zune-jpeg"]
moz_jpeg = ["dep:mozjpeg"]
turbo_jpeg = ["dep:turbojpeg"]
